name: Update Warranty Info Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-warranty:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Warranty Update
        working-directory: public  # Set working directory to public
        shell: pwsh
        env:
          DELL_CLIENT_ID: ${{ secrets.DELL_CLIENT_ID }}
          DELL_CLIENT_SECRET: ${{ secrets.DELL_CLIENT_SECRET }}
          DATTO_API_KEY: ${{ secrets.DATTO_API_KEY }}
          DATTO_API_SECRET: ${{ secrets.DATTO_API_SECRET }}
        run: |
          # Load the function definitions from the public folder.
          . .\Set-WarrantyAPIKeys.ps1
          . .\Update-WarrantyInfo.ps1
          . .\Get-WarrantyInfo.ps1

          # Load the dependent function from the private folder.
          # Since the working directory is public, the private folder is one level up.
          . ..\private\Get-WarrantyDRMM.ps1
          . ..\private\Get-DellWarranty.ps1

          # Now call the functions.
          Set-WarrantyAPIKeys -DellClientID $env:DELL_CLIENT_ID -DellClientSecret $env:DELL_CLIENT_SECRET

          update-warrantyinfo -DattoRMM `
            -DattoAPIURL "https://pinotage-api.centrastage.net" `
            -DattoAPIKey $env:DATTO_API_KEY `
            -DattoAPISecret $env:DATTO_API_SECRET `
            -SyncWithSource `
            -OverwriteWarranty `
            -ExcludeMS `
            -ExcludeHP `
            -ExcludeLenovo `
            -ExcludeApple
